# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-15 17:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='User',
        ),
    ]
