# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-17 18:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_user_user_level'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='page',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='pages_comments', to='register.User'),
            preserve_default=False,
        ),
    ]
