# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-15 20:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes_books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='liked_userss',
            new_name='liked_users',
        ),
    ]
