# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-17 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_level',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
