# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-15 18:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dojo',
            name='age',
        ),
    ]
